// Problem taken from Introduction to Java Programming by Y. Daniel Yang (8th ed.)
// Chapter 3 : Selections
//
// Problem 3.14 : Write a program that randomly generates 0 for a coin head, or 1 for tail.
//                The program should prompt the user to enter 0 or 1, and displays if the
//                user guessed right or not.
//
//
// Author : Giorgio Murad
import javax.swing.JOptionPane;

public class Main {
    public static void main(String[] args) {
        String s;           // String to retrieve user input
        int userGuess;      // Integer inputted by the user
        int sysInt;         // Integer generated by the system
        boolean correct;    // True if the user's guess is correct, false otherwise


        // Generating 1 for heads, or 0 for tails
        sysInt = (int) (Math.random() + 0.5);

        // Prompting the user to guess the generated integer
        s         = JOptionPane.showInputDialog("Enter 0 for heads, or 1 for tails:");
        userGuess = Integer.parseInt(s);
        correct   = (sysInt == userGuess);

        // Displaying Result
        if (correct)
            JOptionPane.showMessageDialog(null, "Your guess is correct :)");
        else
            JOptionPane.showMessageDialog(null, "Your guess is wrong :(");
    }
}